services:
  api:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      seed:
        condition: service_completed_successfully
      redis:
        condition: service_started
      minio:
        condition: service_started

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"

  migrator:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    command: poetry run alembic upgrade head

  seed:
    build: .
    env_file:
      - .env
    depends_on:
      migrator:
        condition: service_completed_successfully
    command: poetry run python -m scripts.seed_users

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: quay.io/minio/aistor/minio:latest
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      seed:
        condition: service_completed_successfully
      redis:
        condition: service_started
      minio:
        condition: service_started
    command: celery -A app.worker.celery_app.celery_app worker --loglevel=info

  celery-beat:
    build: .
    env_file:
      - .env
    depends_on:
      seed:
        condition: service_completed_successfully
      redis:
        condition: service_started
      minio:
        condition: service_started
    command: celery -A app.worker.celery_app.celery_app beat --loglevel=info

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  redis_data:
  minio_data: